apiVersion: v1
kind: Namespace
metadata:
  name: cache
  labels:
    name: cache
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted