apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "redis-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  selector:
    app: redis
    {{- include "redis-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.redis.ports | toYaml | nindent 2 }}
