apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db-chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "db-chart.labels" . | nindent 4 }}
data:
  postgresql.conf: {{ .Values.config.postgresqlConf | toYaml | indent 1 }}
