apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "db-chart.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: {{ required "secret.postgresDb is required" .Values.secret.postgresDb
    | quote }}
  POSTGRES_PASSWORD: {{ required "secret.postgresPassword is required" .Values.secret.postgresPassword
    | quote }}
  POSTGRES_USER: {{ required "secret.postgresUser is required" .Values.secret.postgresUser
    | quote }}
type: Opaque
