apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "redis-chart.labels" . | nindent 4 }}
data:
  redis.conf: {{ .Values.config.redisConf | toYaml | indent 1 }}
