apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis-chart.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "redis-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pvc.storageRequest | quote }}
