apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vote-chart.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "vote-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: vote.dogsvscats.tactful
    http:
      paths:
      - backend:
          service:
            name: '{{ include "vote-chart.fullname" . }}-service'
            port:
              number: 8080
        path: /
        pathType: Prefix
